seed: 42
reproduction_args:
  cudnn.deterministic: True
  cudnn.benchmark: False

num_frames: 16
device: "mps"
image_size: [112, 112, 3]
epochs: 30
evaluation_frequency: 1
lr_steps: [8, 16, 24]
batch_size: 64
max_grad: 20
num_cpu_workers: 8

model: "resnet-50" # accepted values: "resnet-50", "sphereface20", "former-dfer", "swine3dtiny", "convnext-small",
model_configs:
  final_activation: "tanh-sigmoid" # accepted values: "tanh-sigmoid", "double-tanh", "hard-tanh"
  temporal_aggregator: "bi-lstm" # accepted values: "bi-lstm", "bi-gru", "lstm", "gru"
  temporal_aggregation_output_size: 512
backbone_weights: "./models/faceBVAL.pth.tar"
backbone_weights_strict: False # facebval requires False. The rest True is safer.

loss: 'CCC' # accepted values: "CCC", "MSE"
loss_config:
  lambda_ccc: 2
  lambda_v: 1
  lambda_a: 1

optimizer: "SGD"
optimizer_configs:
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.0005

train_list_path: "./support_tables/train_list_lstm.txt"
train_data_path: "../../../Datasets/OMGEmotionChallenge/Train_Set/faces2"
validation_list_path: "./support_tables/validation_list_lstm.txt"
validation_data_path: "../../../Datasets/OMGEmotionChallenge/Validation_Set/trimmed_faces"
ground_truth_path: "./models/former_dfer_1.pth"
shuffle_train_set: True