ground_truth_path: "/Users/leonardoalchieri/Datasets/OMGEmotionChallenge/omg_TestVideos_WithLabels.csv"
data_path: "/Users/leonardoalchieri/Datasets/OMGEmotionChallenge/Test_Set/trimmed_faces"
output_name: test_list_lstm.txt